return {
	{ "ellisonleao/gruvbox.nvim" },
	{ "catppuccin/nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "sainnhe/sonokai" },
	{ "folke/tokyonight.nvim" },
	{ "sainnhe/everforest" },
	{ "sainnhe/edge" },
	{ "sainnhe/gruvbox-material" },
	{ "savq/melange-nvim" },
	{ "navarasu/onedark.nvim" },
	{ "rose-pine/neovim" },
	{ "EdenEast/nightfox.nvim" },
	{ "olimorris/onedarkpro.nvim" },
}
